version = 1

[[annotations]]
path = [
    "REUSE.toml",
    "README.md",
    "src/qt_ui/settings_dialog.ui",
    "src/qt_ui/game_install_dialog.ui"
    
]
precedence = "aggregate"
SPDX-FileCopyrightText = "shadLauncher4 Project"
SPDX-License-Identifier = "GPL-2.0-or-later"

